project_id = "grtxyrucfjucmqebjavi"

[functions.historian-qa]
verify_jwt = true

[functions.overlay-artist]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.unzip-upload]
verify_jwt = true
