project_id = "grtxyrucfjucmqebjavi"

[functions.historian-qa]
verify_jwt = true

[functions.overlay-artist]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.unzip-upload]
verify_jwt = true

[functions.hd-clean-base]
verify_jwt = true

[functions.hd-vectorize]
verify_jwt = true

[functions.hd-export-pack]
verify_jwt = true

[functions.hd-bake-overlay]
verify_jwt = true
